name: neo2-8-12-2019

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint
    - name: Clone source
      run: |
        cd /home/runner
        git clone https://github.com/coolsnowwolf/lede.git
        sudo chmod -R 777 lede
        sudo chown -R runner:runner lede
        cd /home/runner/lede
        ./scripts/feeds update -a 
        ./scripts/feeds install -a
    - name: Change theme
      run: |
        cd /home/runner/lede/package/lean
        rm -rf luci-theme-argon
        git clone https://github.com/jerrykuku/luci-theme-argon.git
        sed -i 's/luci-theme-bootstrap/luci-theme-argon/g' '/home/ubuntu/neo2/lede/feeds/luci/collections/luci/Makefile'
    - name: Clone Adguardhome
      run: |
        cd /home/runner/lede/package/lean
        git clone https://github.com/Mattaclp/luci-app-adguardhome
        git clone https://github.com/happyzhang1995/openwrt-adguardhome
    - name: Clone config
      run: |
        cd /home/runner/lede/
        wget https://raw.githubusercontent.com/wky0211/build-test/master/.config
    - name: Build
      run: | 
        cd /home/runner/lede 
        make -j2
    - uses: actions/upload-artifact@master
      with:
        name: result
        path: /home/runner/lede/bin
